//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab10
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lab10Entities : DbContext
    {
        public lab10Entities()
            : base("name=lab10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Confidential> Confidential { get; set; }
        public virtual DbSet<Confidential_Biba> Confidential_Biba { get; set; }
        public virtual DbSet<Secret> Secret { get; set; }
        public virtual DbSet<Secret_Biba> Secret_Biba { get; set; }
        public virtual DbSet<TopSecret> TopSecret { get; set; }
        public virtual DbSet<TopSecret_Biba> TopSecret_Biba { get; set; }
        public virtual DbSet<Unclassified> Unclassified { get; set; }
        public virtual DbSet<Unclassified_Biba> Unclassified_Biba { get; set; }
    }
}
